export const images = [
  { path: "../images/1.jpg" },
  { path: "../images/2.png" },
  { path: "../images/3.jpg" },
  { path: "../images/4.png" },
  { path: "../images/5.jpg" },
  { path: "../images/6.png" },
  { path: "../images/7.jpg" },
  { path: "../images/8.png" },
  { path: "../images/9.jpg" },
  { path: "../images/10.png" },
  { path: "../images/11.jpg" },
  { path: "../images/12.png" },
  { path: "../images/13.jpg" },
  { path: "../images/14.png" },
  { path: "../images/15.jpg" },
  { path: "../images/16.png" },
  { path: "../images/17.jpg" },
  { path: "../images/18.png" },
  { path: "../images/19.jpg" },
  { path: "../images/20.jng" },
]
